### ISSUE TITLE
Social Media Logo Not Centered

### ISSUE THREAD

**Issue by ralphvirtucio** [ralphvirtucio/huddle-landing-page-with-single-inductory-section#1]
I applied the flex property on my list item element but I think my social media logo is not centered in the list item container, Why it is not centered?

**Comment by abitsalihu** [comment]
@ralphvirtucio I would like to help you with this issue. :)

**Comment by ralphvirtucio** [comment]
You can check the style.css code. thanks

**Comment by ralphvirtucio** [comment]
> @ralphvirtucio Do you want me to fix it and I can make a PR, or do you just want me to tell u?

you can just tell me.

**Comment by abitsalihu** [comment]
@ralphvirtucio They're not displayed in center because the icons are inside the <a> link, and the <a> link container is bigger than the icons so the icons are not displayed in center inside the <a> container.

add this code to the <a> links directly or by giving them classes so the other <a> links don't get affected!

```
a{
display:flex
}
```

Below is a video explaining why they're not aligned, I added a "border:1px solid red;" and a "display: flex; " property on the <a> link for you to see it:


https://user-images.githubusercontent.com/94648837/191083299-14ae9a7a-9117-433b-b666-cf9a79500624.mov
